#!/usr/bin/env python3
"""Discover available skills, MCPs, plugins, and templates.

Scans the Claude Code environment and writes a capabilities manifest
to context/capabilities.md for the orchestrator to read.

Usage:
    python3 lib/discover.py              # Write context/capabilities.md
    python3 lib/discover.py --print      # Print to stdout only
"""

from __future__ import annotations

import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

CLAUDE_DIR = Path.home() / ".claude"
CLAUDE_JSON = Path.home() / ".claude.json"
SKILLS_DIR = CLAUDE_DIR / "skills"
CLAIVE_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = CLAIVE_ROOT / "templates"
PIPELINES_DIR = CLAIVE_ROOT / "pipelines" / "examples"
OUTPUT = CLAIVE_ROOT / "context" / "capabilities.md"


def parse_skill_frontmatter(skill_path: Path) -> dict | None:
    """Extract name and description from SKILL.md frontmatter."""
    try:
        text = skill_path.read_text()
    except OSError:
        return None

    match = re.match(r"^---\s*\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return None

    fm = match.group(1)
    result = {"name": skill_path.parent.name}

    for key in ("name", "description"):
        # Handle multi-line YAML values (folded with >)
        pattern = rf"^{key}:\s*>?\s*\n?(.*?)(?=\n\w|\n---|\Z)"
        m = re.search(pattern, fm, re.MULTILINE | re.DOTALL)
        if m:
            val = m.group(1).strip()
            # Collapse multi-line into single line
            val = re.sub(r"\s+", " ", val)
            result[key] = val
        else:
            # Simple single-line value
            m = re.search(rf"^{key}:\s*(.+)", fm, re.MULTILINE)
            if m:
                result[key] = m.group(1).strip().strip("\"'")

    return result if "description" in result else None


def discover_skills() -> list[dict]:
    """Find all skills in ~/.claude/skills/."""
    skills = []
    if not SKILLS_DIR.is_dir():
        return skills

    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        skill_md = skill_dir / "SKILL.md"
        if skill_md.is_file():
            info = parse_skill_frontmatter(skill_md)
            if info:
                skills.append(info)
    return skills


def discover_mcps() -> tuple[list[dict], list[dict], list[dict]]:
    """Find MCP servers from ~/.claude.json and Claude.ai connections.

    Returns (local_mcps, cloud_mcps, plugins).
    """
    local_mcps = []
    cloud_mcps = []
    plugins = []

    # Local MCP servers from ~/.claude.json
    if CLAUDE_JSON.is_file():
        try:
            cfg = json.loads(CLAUDE_JSON.read_text())
            for name, srv in cfg.get("mcpServers", {}).items():
                cmd = srv.get("command", "?")
                args = srv.get("args", [])
                # Extract package name from args
                pkg = ""
                for a in args:
                    if a.startswith("@") or a.startswith("mcp-"):
                        pkg = a
                        break
                local_mcps.append({"name": name, "command": cmd, "package": pkg})

            # Claude.ai MCPs
            for name in cfg.get("claudeAiMcpEverConnected", []):
                cloud_mcps.append({"name": name})
        except (json.JSONDecodeError, OSError):
            pass

    # Plugins from settings.json
    settings = CLAUDE_DIR / "settings.json"
    if settings.is_file():
        try:
            cfg = json.loads(settings.read_text())
            for p in cfg.get("enabledPlugins", []):
                plugins.append({"id": p})
        except (json.JSONDecodeError, OSError):
            pass

    return local_mcps, cloud_mcps, plugins


def discover_templates() -> list[dict]:
    """Find agent team templates."""
    templates = []
    if not TEMPLATES_DIR.is_dir():
        return templates

    for f in sorted(TEMPLATES_DIR.glob("*.yaml")):
        try:
            text = f.read_text()
            name = f.stem
            desc = ""
            m = re.search(r"^description:\s*(.+)", text, re.MULTILINE)
            if m:
                desc = m.group(1).strip()
            agents = re.findall(r"^\s{2}(\w+):", text, re.MULTILINE)
            templates.append({"name": name, "description": desc, "agents": agents})
        except OSError:
            pass
    return templates


def discover_pipelines() -> list[str]:
    """Find example pipeline YAMLs."""
    if not PIPELINES_DIR.is_dir():
        return []
    return sorted(f.stem for f in PIPELINES_DIR.glob("*.yaml"))


def render(skills, local_mcps, cloud_mcps, plugins, templates, pipelines) -> str:
    """Render the capabilities manifest as markdown."""
    lines = [
        "# Available Capabilities",
        "",
        f"*Auto-generated by `claive discover` on {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
    ]

    # Skills
    lines.append(f"## Skills ({len(skills)})")
    lines.append("")
    lines.append("Invoke with `/skill-name` in agent prompts.")
    lines.append("")
    if skills:
        for s in skills:
            desc = s.get("description", "")
            # Truncate long descriptions to first sentence
            first_sentence = re.split(r"(?<=\.)\s", desc, maxsplit=1)[0]
            if len(first_sentence) > 120:
                first_sentence = first_sentence[:117] + "..."
            lines.append(f"- **/{s['name']}** — {first_sentence}")
    else:
        lines.append("*None found in ~/.claude/skills/*")
    lines.append("")

    # MCP Servers
    total_mcps = len(local_mcps) + len(cloud_mcps)
    lines.append(f"## MCP Servers ({total_mcps})")
    lines.append("")
    lines.append("Available to all agents automatically.")
    lines.append("")
    if local_mcps:
        for m in local_mcps:
            pkg = f" (`{m['package']}`)" if m["package"] else ""
            lines.append(f"- **{m['name']}**{pkg}")
    if cloud_mcps:
        for m in cloud_mcps:
            lines.append(f"- **{m['name']}** (cloud)")
    if not local_mcps and not cloud_mcps:
        lines.append("*None configured*")
    lines.append("")

    # Plugins
    if plugins:
        lines.append(f"## Plugins ({len(plugins)})")
        lines.append("")
        for p in plugins:
            # Clean up plugin ID for display
            pid = p["id"]
            name = pid.split("@")[0] if "@" in pid else pid
            source = pid.split("@")[1] if "@" in pid else ""
            lines.append(f"- **{name}** ({source})" if source else f"- **{name}**")
        lines.append("")

    # Templates
    if templates:
        lines.append(f"## Agent Templates ({len(templates)})")
        lines.append("")
        for t in templates:
            agents = ", ".join(t["agents"][:6]) if t["agents"] else "—"
            desc = f" — {t['description']}" if t["description"] else ""
            lines.append(f"- **{t['name']}**{desc} [{agents}]")
        lines.append("")

    # Example Pipelines
    if pipelines:
        lines.append(f"## Example Pipelines ({len(pipelines)})")
        lines.append("")
        for p in pipelines:
            lines.append(f"- `pipelines/examples/{p}.yaml`")
        lines.append("")

    return "\n".join(lines)


def main():
    print_only = "--print" in sys.argv

    skills = discover_skills()
    local_mcps, cloud_mcps, plugins = discover_mcps()
    templates = discover_templates()
    pipelines = discover_pipelines()

    output = render(skills, local_mcps, cloud_mcps, plugins, templates, pipelines)

    if print_only:
        print(output)
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(output)
        print(f"Wrote {OUTPUT} ({len(skills)} skills, "
              f"{len(local_mcps) + len(cloud_mcps)} MCPs, "
              f"{len(plugins)} plugins, "
              f"{len(templates)} templates)")


if __name__ == "__main__":
    main()
